name: 'image-compressor'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-FUN-400-PAR-4-1-compressor-lou.onezime.git"
  EXECUTABLE: "imageCompressor"
  ARGUMENTS: "-n 2 -l 0.8 -f in"

jobs:
  check_stack_build:
    name: "verify that stack is successfully built"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check stack
        timeout-minutes: 5
        run: |
          sudo make re

  check_program_compilation:
    name: "verify that EXECUTABLE environment variable exists and is executable"
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - run: sudo make
        timeout-minutes: 5
      - run: make clean
      - run: |
          OIFS=$IFS
          IFS=' '
          for x in $EXECUTABLES
            do
              ./$x $ARGUMENTS
            done
          IFS=$OIFS
          if [[ -n $EXECUTABLES ]]
          then
            echo Program not compiled properly
          fi

  push_to_mirror:
    needs: [check_program_compilation, check_stack_build]
    if: ${{ github.event_name == 'push' }}
    name: "pushes all files to mirror specified"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
