name: Push mirror

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-OOP-400-PAR-4-1-tekspice-martin.fillon.git"

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.KEY }}
